labelPRBasedOnFilePath:
  "Pkg: shared":
    - packages/shared/**/*
  "Pkg: design-system":
    - packages/design-system/**/*
  "Pkg: sagas":
    - packages/sagas/**/*
  "Pkg: shared-modules":
    - packages/shared-modules/**/*
  "App: wallet":
    - packages/wallet/**/*
  "App: web":
    - packages/web/**/*
