version: 2.1

executors:
  docker:
    docker:
      - image: circleci/node:11.14.0
    working_directory: /home/circleci/app

  docker-browsers:
    docker:
      - image: circleci/node:11.14.0-browsers
    working_directory: /home/circleci/app

jobs:
  ## Web package related jobs

  web_install-lint-test:
    # install and lint is taken as one job to remove required time for downloading cache
    executor: docker

    steps:
      # Download and cache dependencies
      - checkout
      - run: yarn update-submodules
      # Installation
      - run: yarn --frozen-lockfile
      # Confirm Artifact Version
      - run: yarn workspace @neufund/web contract-artifacts:check
      # Danger
      - run: yarn workspace @neufund/web danger ci
      # Linting
      - run: yarn workspace @neufund/web lint
      - run: yarn workspace @neufund/shared-utils lint
      - run: yarn workspace @neufund/design-system lint
      # Unit Tests
      - run: yarn workspace @neufund/web test
      - run: yarn workspace @neufund/shared-utils test

      - save_cache:
          paths:
            - node_modules
            - packages/web/app/lib/contracts
            - /home/circleci/.cache/Cypress
          key: v33-deps-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: /home/circleci/app/packages/web
          paths:
            - ./e2e-test-tags

  web_build-docker-test-e2e:
    executor: docker-browsers

    parallelism: 4

    steps:
      - checkout
      - restore_cache:
          keys:
            - v33-deps-{{ checksum "package.json" }}
            - v33-deps-

      - attach_workspace:
          at: /home/circleci/app/packages/web

      - run: yarn --frozen-lockfile
      - run: yarn workspace @neufund/web show:tags
      - run:
          command: yarn workspace @neufund/web build:prod:e2e:io
          no_output_timeout: 10m
      - run:
          command: yarn workspace @neufund/web test:e2e:chrome

  web_build:
    executor: docker

    steps:
      - checkout
      - restore_cache:
          keys:
            - v33-deps-{{ checksum "package.json" }}
            - v33-deps-

      - run: yarn --frozen-lockfile
      - run:
          command: yarn workspace @neufund/web build:prod:e2e
          no_output_timeout: 10m
      # If build takes more than 10mins then fail
      - persist_to_workspace:
          root: /home/circleci/app
          paths:
            - ./

  web_test-e2e:
    machine:
      enabled: true
      image: ubuntu-1604:201903-01
      docker_layer_caching: true

    environment:
      COMPOSE_INTERACTIVE_NO_CLI: 1

    parallelism: 3

    working_directory: /home/circleci/app

    steps:
      - attach_workspace:
          at: /home/circleci/app
      - run: ./.circleci/install-yarn.sh
      - restore_cache:
          keys:
            - v33-deps-{{ checksum "package.json" }}
            - v33-deps-

      - run:
          command: source /opt/circleci/.nvm/nvm.sh && yarn workspace @neufund/web test:e2e
          no_output_timeout: 30m

  web_codechecks:
    executor: docker

    steps:
      - checkout
      - restore_cache:
          keys:
            - v33-deps-{{ checksum "package.json" }}
            - v33-deps-

      - run: yarn --frozen-lockfile
      - run: yarn workspace @neufund/web build:commit-deployment
      - run: yarn workspace @neufund/web codechecks

  web_codechecks-vis-reg:
    executor: docker-browsers

    steps:
      - checkout
      - restore_cache:
          keys:
            - v33-deps-{{ checksum "package.json" }}
            - v33-deps-

      - run: yarn --frozen-lockfile
      - run: yarn workspace @neufund/web storybook:screenshots
      - run: yarn workspace @neufund/web codechecks ./codechecks-vis-reg.ts

  web_codechecks-e2e-vis-reg:
    executor: docker-browsers

    steps:
      - checkout
      - restore_cache:
          keys:
            - v33-deps-{{ checksum "package.json" }}
            - v33-deps-

      - run: yarn --frozen-lockfile
      - run:
          command: yarn workspace @neufund/web build:prod:e2e:io
          no_output_timeout: 10m
      - run:
          command: yarn workspace @neufund/web test:e2e:vis-reg
      - run: yarn workspace @neufund/web codechecks ./codechecks-e2e-vis-reg.ts

  deploy-storybook:
    executor: docker

    steps:
      - checkout
      - restore_cache:
          keys:
            - v33-deps-{{ checksum "package.json" }}
            - v33-deps-

      - run: yarn --frozen-lockfile
      - run: yarn storybook-to-ghpages --script=storybook:build --ci --host-token-env-variable=DANGER_GITHUB_API_TOKEN --packages packages

  ## Mobile package related jobs

  mobile_install-lint-test:
    # install and lint is taken as one job to remove required time for downloading cache
    executor: docker

    steps:
      # Download and cache dependencies
      - checkout
      - run: yarn update-submodules
      # Installation
      - run: yarn --frozen-lockfile
      # Linting
      - run: yarn workspace @neufund/wallet lint
      # Unit Tests
      - run: yarn workspace @neufund/wallet test

workflows:
  version: 2

  web:
    jobs:
      - web_install-lint-test
      - web_build-docker-test-e2e:
          requires:
            - web_install-lint-test
      - web_build:
          requires:
            - web_install-lint-test
      - web_test-e2e:
          requires:
            - web_build
      - web_codechecks:
          requires:
            - web_install-lint-test
      - web_codechecks-vis-reg:
          requires:
            - web_install-lint-test
      - web_codechecks-e2e-vis-reg:
          requires:
            - web_install-lint-test

  mobile:
    jobs:
      - mobile_install-lint-test

  nightly:
    triggers:
      - schedule:
          cron: "0 5 * * *"
          filters:
            branches:
              only:
                - master
                - production

    jobs:
      - web_install-lint-test
      - web_build-docker-test-e2e:
          requires:
            - web_install-lint-test
      - web_build:
          requires:
            - web_install-lint-test
      - web_test-e2e:
          requires:
            - web_build
            - web_build-docker-test-e2e
      - web_codechecks:
          requires:
            - web_build
      - web_codechecks-vis-reg:
          requires:
            - web_build
      - web_codechecks-e2e-vis-reg:
          requires:
            - web_build

  deploy-storybook:
    jobs:
      - deploy-storybook:
          filters:
            branches:
              only: master
